import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// TODO: First check if you can make pupeeter and mongodb work on the Vercel or Github page before geting to it
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>The Header</header>
        {children}
        <footer>The Footer</footer>
      </body>
    </html>
  );
}
